/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.tarea2poo;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vascl
 */
public class CrearVentaServicio extends javax.swing.JDialog {

    private int idFactura;
    private String codigoCliente;
    private String idOrdenTrabajo;
    private Conexion connect;

    /**
     * Creates new form CrearVentaServicio
     */
    public CrearVentaServicio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public CrearVentaServicio(java.awt.Frame parent, boolean modal, int idFactura, String codigoCliente,
            String idOrdenTrabajo, String tipo, Conexion connect) {
        super(parent, modal);
        initComponents();
        this.codigoCliente = codigoCliente;
        this.idFactura = idFactura;
        this.idOrdenTrabajo = idOrdenTrabajo;
        jLabel1.setText(tipo);
        this.connect = connect;
        llenarTabladeProductosoServicios();
    }

    private void llenarTabladeProductosoServicios() {

        if (jLabel1.getText().equals("Venta")) {
            try {
                Connection con = connect.getCnx();
                String query = "SELECT * FROM inventario";
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(query);
                DefaultTableModel model = new DefaultTableModel();
                model.addColumn("Codigo");
                model.addColumn("Codigo Proveedor");
                model.addColumn("Nombre");
                model.addColumn("Precio");
                model.addColumn("Existencia");
                while (rs.next()) {
                    int CodigoProducto = rs.getInt("CodigoProducto");
                    int CodigoProveedor = rs.getInt("CodigoProveedor");
                    String NombreDeProducto = rs.getString("NombreDeProducto");
                    float PrecioVenta = rs.getFloat("PrecioVenta");
                    int Existencia = rs.getInt("Existencia");

                    model.addRow(new Object[] { CodigoProducto, CodigoProveedor, NombreDeProducto, PrecioVenta,
                            Existencia });
                }

                jTableProductos_Servicios.setModel(model);

            } catch (Exception e) {
                // TODO: handle exception
            }

        } else if (jLabel1.getText().equals("Servicio")) {
            try {

                Connection con = connect.getCnx();
                String query = "SELECT * FROM servicio";
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(query);
                DefaultTableModel model = new DefaultTableModel();
                model.addColumn("Id");
                model.addColumn("Nombre");
                model.addColumn("Precio");

                while (rs.next()) {
                    int IdServicio = rs.getInt("IdServicio");
                    String Nombre = rs.getString("Nombre");
                    float Precio = rs.getFloat("Precio");

                    model.addRow(new Object[] { IdServicio, Nombre, Precio });
                }
                jTableProductos_Servicios.setModel(model);

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error al conectar con la base de datos" + e.getMessage());
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos_Servicios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonAgregar_a_Factura = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableItemsFactura = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButtonCrearFactura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(jTableProductos_Servicios);

        jLabel1.setText("jLabel1");

        jButtonAgregar_a_Factura.setText("Agregar a Factura");
        jButtonAgregar_a_Factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregar_a_FacturaActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTableItemsFactura);

        jLabel2.setText("Factura");

        jButtonCrearFactura.setText("Crear Factura");
        jButtonCrearFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(50, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonAgregar_a_Factura)
                                        .addComponent(jLabel1)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonCrearFactura)
                                        .addComponent(jLabel2))
                                .addContainerGap(50, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAgregar_a_Factura)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCrearFactura)
                                .addContainerGap(19, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregar_a_FacturaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCrearFacturaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearVentaServicio.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearVentaServicio.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearVentaServicio.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearVentaServicio.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrearVentaServicio dialog = new CrearVentaServicio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar_a_Factura;
    private javax.swing.JButton jButtonCrearFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableItemsFactura;
    private javax.swing.JTable jTableProductos_Servicios;
    // End of variables declaration//GEN-END:variables
}
