package com.mycompany.tarea2poo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author gl_admin
 */
public class OrdenTrabajo extends javax.swing.JFrame {

    Conexion connect;
    
    private int codigoempleado = 0;
    private int idcliente = 0;
    public OrdenTrabajo() {
        initComponents();
        connect = new Conexion();
        Update_EmployeeCombo();
    }

    public OrdenTrabajo(int _idcliente)
    {
        this.idcliente = _idcliente;
        initComponents();
        connect = new Conexion();
        Update_EmployeeCombo();
    }
    
    private void Update_EmployeeCombo()
    {
        var sql = "SELECT * FROM Empleado Where inactivo = False";
        try 
        {
          Connection cnn = connect.getCnx();
          Statement stm = cnn.createStatement();
          ResultSet rs = stm.executeQuery(sql);
          DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

          model.addElement("Seleccione un empleado");
          
            while (rs.next()) 
            {
                int CodigoCliente_ = rs.getInt("CodigoEmpleado");
                String nombre = rs.getString("Nombre");
                String telefono = rs.getString("telefono");
                model.addElement(CodigoCliente_ + ":" + nombre + " - " + telefono);
            }
          combo_empleado.setModel(model);
          
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error retrieving Empleados: " + e.getMessage());
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo_empleado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tobservacion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        combo_empleado.setName("combo_empleado"); // NOI18N
        combo_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_empleadoActionPerformed(evt);
            }
        });

        jLabel1.setText("Empleado asignado:");

        jLabel2.setText("ORDEN DE TRABAJO:");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Tobservacion.setColumns(20);
        Tobservacion.setRows(5);
        jScrollPane2.setViewportView(Tobservacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(combo_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_empleado)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(this.codigoempleado <= 0)
        {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un empleado");
            return;
        }
        
        Connection cnn = connect.getCnx();
        String observacion = Tobservacion.getText();
        
        String  sql = "Insert into ordendetrabajo (CodigoEmpleado, Observaciones) Values(?,?)";
        try 
        {
          PreparedStatement pst = cnn.prepareStatement(sql);
          pst.setInt(1, this.codigoempleado);
          pst.setString(2, observacion);
          pst.executeUpdate();
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "ErrorSQL " + e.getMessage());
        }
        
        if(this.idcliente > 0)
        {
            String query = "SELECT IdOrdenTrabajo from Ordendetrabajo where observaciones = '"+ observacion +"' order by IdOrdenTrabajo desc Limit 1";
            try 
            {
              Statement stm = cnn.createStatement();
              ResultSet rs = stm.executeQuery(query);
              int id = 0;
              if(rs.next())
              {
                  id = rs.getInt("IdOrdenTrabajo");
              }
              if(id > 0)
              {
                String factura = "INSERT into Facturas (CodigoCliente, IdOrdenTrabajo) Values(?,?)";
                PreparedStatement ps = cnn.prepareStatement(factura);
                ps.setInt(1, this.idcliente);
                ps.setInt(2, id);
                ps.executeUpdate();
                cnn.close();
                this.setVisible(false);
              }
            } 
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, "ErrorSQL " + e.getMessage());
            }
            
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combo_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_empleadoActionPerformed
        String texto = combo_empleado.getSelectedItem().toString();
   
        if ("Seleccione un empleado".equals(texto)) {
            this.codigoempleado = -1;
            return;
        }
        
        String[] partes1 = texto.split(":");

        int id = Integer.parseInt(partes1[0]);
        this.codigoempleado = id;
    }//GEN-LAST:event_combo_empleadoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdenTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdenTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdenTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdenTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdenTrabajo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Tobservacion;
    private javax.swing.JComboBox<String> combo_empleado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
